/*Question_2 Answer */

SELECT L.MARKETING_CHANNEL ,AVG( DATEDIFF('Day', L.LEAD_CREATED_DATE, S.CASE_CLOSED_SUCCESSFUL_DATE ) ) AS AVG_TIME_CHANNEL
FROM MAIN.LEADS L 
JOIN MAIN.SALES_FUNNEL S ON L.LEAD_ID = S.LEAD_ID  
WHERE S.SALES_FUNNEL_STEPS  = 'PV System Sold'
GROUP BY L.MARKETING_CHANNEL 
ORDER BY 2 DESC
LIMIT 1

/*Question_2 Answer */





SELECT L.MARKETING_CHANNEL AS CHANNEL, COUNT(L.LEAD_ID)
FROM LEADS L
GROUP BY L.MARKETING_CHANNEL

SELECT *
FROM LEADS L

SELECT *
FROM SALES_FUNNEL S
WHERE S.LEAD_ID IN(
'fc310c4353253e1',
'7279187e044ec5a'
)
ORDER BY 1


Select s.SALES_FUNNEL_STEPS, Count(l.lead_id)

from  MAIN.Sales_funnel s 

join leads l on s.LEAD_ID= l.LEAD_ID 
Where s.Sales_funnel_Steps = 'PV System Sold' 

GROUP BY s.SALES_FUNNEL_STEPS


SELECT *
FROM
(
SELECT L.MARKETING_CHANNEL AS CHANNEL, COUNT(S.LEAD_ID) AS LEADS
FROM LEADS L
JOIN SALES_FUNNEL S ON L.LEAD_ID = S.LEAD_ID
WHERE S.SALES_FUNNEL_STEPS = 'PV System Sold'
GROUP BY L.MARKETING_CHANNEL
) AS CONVERTED_LEADS 













WITH 
TOTAL_LEADS AS (

SELECT L.MARKETING_CHANNEL AS CHANNEL, COUNT(L.LEAD_ID) AS LEADS
FROM MAIN.LEADS L
GROUP BY L.MARKETING_CHANNEL
),
CONVERTED_LEADS AS(
SELECT L.MARKETING_CHANNEL AS CHANNEL, COUNT(S.LEAD_ID) AS LEADS
FROM MAIN.LEADS L
JOIN MAIN.SALES_FUNNEL S ON L.LEAD_ID = S.LEAD_ID
WHERE S.SALES_FUNNEL_STEPS = 'PV System Sold'
GROUP BY L.MARKETING_CHANNEL
)
SELECT TL.CHANNEL, TL.LEADS AS TOTAL_LEADS, CL.LEADS AS CONVERTED_LEADS, ( (CL.LEADS / TL.LEADS) * 100 ) AS CONVERSION_RATE
FROM TOTAL_LEADS AS TL
JOIN CONVERTED_LEADS AS CL ON TL.CHANNEL  = CL.CHANNEL
ORDER BY 4 DESC
LIMIT 1





SELECT S.LEAD_ID 
FROM MAIN.SALES_FUNNEL S
WHERE S.LEAD_ID = 'fc310c4353253e1'

SELECT *
FROM MAIN.SALES_FUNNEL S
WHERE S.LEAD_ID IN(
'fc310c4353253e1',
'7279187e044ec5a'
)
ORDER BY 1, 2




/*WITH TIME_DATA AS 
(
SELECT OP.LEAD_ID, OP.CASE_OPENED_DATE AS OPEN_DATE , CL.CASE_CLOSED_SUCCESSFUL_DATE AS CLOSE_DATE, DATEDIFF('Day', OP.CASE_OPENED_DATE, CL.CASE_CLOSED_SUCCESSFUL_DATE ) AS TIME_TAKEN
FROM 
(
SELECT S.LEAD_ID, S.CASE_OPENED_DATE 
FROM MAIN.sales_funnel S 
WHERE S.SALES_FUNNEL_STEPS  = 'Sales Call 1'
) AS OP
JOIN 
(
SELECT S.LEAD_ID, S.CASE_CLOSED_SUCCESSFUL_DATE 
FROM MAIN.sales_funnel S 
WHERE S.SALES_FUNNEL_STEPS  = 'PV System Sold'
) AS CL 
ON OP.LEAD_ID = CL.LEAD_ID
)
SELECT L.MARKETING_CHANNEL , AVG(TD.TIME_TAKEN ) AS AVERAGE_TIME_CONVERSION
FROM TIME_DATA TD 
JOIN main.LEADS L ON TD.LEAD_ID = L.LEAD_ID 
GROUP BY L.MARKETING_CHANNEL 
ORDER BY 2 DESC*/






SELECT *
FROM MAIN.SALES_FUNNEL S
WHERE S.LEAD_ID IN(
'fc310c4353253e1',
'7279187e044ec5a'
)
ORDER BY 1, 2


SELECT *

FROM MAIN.LEADS L 

JOIN MAIN.SALES_FUNNEL S ON L.LEAD_ID = S.LEAD_ID

WHERE S.LEAD_ID IN(
'fc310c4353253e1',
'7279187e044ec5a'
)





--THERE ARE A FEW RECORDS THAT HAVE CASE_CLOSED_SUCCESSFUL_DATE AS 'NULL'  DO THEY COUNT AS ANOMALIES OR ARE WE SUPPOSED TO REMOVE THEM FROM THE QUERY?

--CREATE TABLE NEW_TABLE (ID INT, NAME VARCHAR(30) )




