

/*Question_3 Answer */


(SELECT L.MARKETING_CHANNEL,  L.LEAD_CREATED_DATE , S.CASE_CLOSED_SUCCESSFUL_DATE, DATEDIFF('Day', L.LEAD_CREATED_DATE , S.CASE_CLOSED_SUCCESSFUL_DATE) AS Date_Diff , Count(L.LEAD_ID)

FROM MAIN.LEADS L

JOIN MAIN.SALES_FUNNEL S ON L.LEAD_ID = S.LEAD_ID 

WHERE S.SALES_FUNNEL_STEPS = 'Sales Call 1' 

GROUP BY  L.LEAD_CREATED_DATE, L.MARKETING_CHANNEL, S.CASE_CLOSED_SUCCESSFUL_DATE
ORDER BY Date_Diff ASC
LIMIT 3)

UNION ALL

(SELECT L.MARKETING_CHANNEL,  L.LEAD_CREATED_DATE , S.CASE_CLOSED_SUCCESSFUL_DATE, DATEDIFF('Day', L.LEAD_CREATED_DATE , S.CASE_CLOSED_SUCCESSFUL_DATE) AS Date_Diff , Count(L.LEAD_ID)

FROM MAIN.LEADS L

JOIN MAIN.SALES_FUNNEL S ON L.LEAD_ID = S.LEAD_ID 

WHERE S.SALES_FUNNEL_STEPS = 'Sales Call 1' 

GROUP BY  L.LEAD_CREATED_DATE, L.MARKETING_CHANNEL, S.CASE_CLOSED_SUCCESSFUL_DATE
ORDER BY Date_Diff DESC
LIMIT 3)





















With TOTAL_LEADS AS
(

SELECT  L.MARKETING_CHANNEL AS CHANNEL , COUNT(L.LEAD_ID) as Leads

FROM MAIN.LEADS L

GROUP BY   L.MARKETING_CHANNEL 

),

CONVERTED_LEADS AS (

SELECT  L.MARKETING_CHANNEL AS CHANNEL , COUNT(L.LEAD_ID) as Leads

FROM MAIN.LEADS L

JOIN MAIN.SALES_FUNNEL S ON L.LEAD_ID = S.LEAD_ID 

WHERE S.SALES_FUNNEL_STEPS = 'Sales Call 1' 

GROUP BY  L.MARKETING_CHANNEL

)



SELECT TL.CHANNEL, TL.LEADS AS TOTAL_LEADS, CL.LEADS AS CONVERTED_LEADS, ( (CL.LEADS / TL.LEADS) * 100 ) AS CONVERSION_RATE
FROM TOTAL_LEADS AS TL
LEFT JOIN CONVERTED_LEADS  AS CL ON TL.CHANNEL  = CL.CHANNEL









