CREATE OR REPLACE TABLE Time_Conversion AS 

SELECT L.LEAD_ID, L.MARKETING_CHANNEL,  L.LEAD_CREATED_DATE ,DATE_TRUNC('month', l.LEAD_CREATED_DATE) AS COHORT_MONTH, S.CASE_OPENED_DATE,  S.CASE_CLOSED_SUCCESSFUL_DATE ,  S.SALES_FUNNEL_STEPS, 

CASE 
	WHEN S.CASE_CLOSED_SUCCESSFUL_DATE IS NOT NULL THEN 1
	ELSE 0
END AS IS_CONVERTED,

DATEDIFF('day', L.LEAD_CREATED_DATE, S.CASE_CLOSED_SUCCESSFUL_DATE) AS DAYS_TO_SUCCESS

FROM MAIN.LEADS L


JOIN MAIN.SALES_FUNNEL S ON L.LEAD_ID = S.LEAD_ID 





SELECT * 
FROM MAIN.Time_Conversion tc 




CREATE OR REPLACE TABLE Cohort_Analysis AS 


SELECT COHORT_MONTH ,  MARKETING_CHANNEL, Count(LEAD_ID), SUM(IS_CONVERTED) AS TOTAL_CONVERSION, ROUND(SUM(IS_CONVERTED)/ Count(LEAD_ID)*100 ) AS CONVERSION_RATE_PCT, ROUND(AVG(DAYS_TO_SUCCESS), 1) AS AVG_DATE_CONVERT
FROM Time_Conversion 

GROUP BY COHORT_MONTH, MARKETING_CHANNEL



SELECT * 
FROM MAIN.Cohort_Analysis 